version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: sh -c "cd /usr/src/app/backend && nodemon src/server.js"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
    command: sh -c "cd /usr/src/app/frontend && ng serve --host 0.0.0.0 --port 4200"
