version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    working_dir: /usr/src/app/backend
    command: sh -c "nodemon src/server.js"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    working_dir: /usr/src/app/frontend
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"